data:
  base: 30
  oos_path: data/oos_data_2^22.npy
  test_path: data/test_data_2^22.npy
  train_path: data/train_data_2^22.npy
io:
  checkpoint_every: 200
  evaluate_every: 1
  evaluate_final: true
  save_path: ./models/factorization/2^22/big_run_initial_test/
loader:
  oos:
    batch_size: 256
    shuffle: false
  test:
    batch_size: 256
    shuffle: false
  train:
    batch_size: 256
    random_sampling: true
metrics:
  max_num: -1
  n_beams: 2
  save_suffix: ''
  temperature: 1.0
model_args:
  attn_weight_xavier_init_constant: 0.5
  dim_feedforward: 1024
  dropout: 0.1
  embed_dim: 256
  embedding_initialization: xavier
  extra_positional_encoding_relative_decoder_mha: true
  learn_positional_encoding: true
  max_decode_size: 64
  norm_first: false
  num_decoder_layers: 10
  num_encoder_layers: 10
  positional_encoding_query_key_only: false
  positional_encoding_type: relative-transfxl
  repeat_positional_encoding: false
  scale_embeddings: false
  scale_embeddings_at_init: false
  shared_embeddings: false
optimizer:
  gradient_accumulation_steps: 8
  max_grad_norm: 1
  opt_args:
    lr: 0.001
    weight_decay: 0.1
  type: AdamW
problem_type: factorization
resume_training: false
scheduler:
  max_steps: -1
  nb_epochs: 200
  scheduler_args:
    nb_steps: 389150
    num_warmup_steps: 1200
  type: get_linear_schedule_with_warmup
tokenizer:
  n_tokens: 34
  pad_token_id: 31
verbose: true
wandb:
  enabled: true
  entity: sims-s
  id: 225hf5mx
  project: integer-factorization
  watch_args:
    log: all
    log_freq: 50
